import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createDemoServer } from '../apps/demo-server/server'

/** Offline examples are generated by the real engine, including valid event hashes. */
async function main(): Promise<void> {
  const { client } = createDemoServer({ secretKey: 'offline-fixture-key-not-for-live-use', governance: { clock: () => Date.now() } })
  const metadata = { actor: 'demo-agent', timestamp: Date.now() }
  const lookup = await client.submitIntent({ id: 'capability-source-demo', type: 'lookup_instance_cost', payload: { resourceId: 'i-0000016' }, metadata })
  if (!lookup.capabilities) throw new Error('Missing source capability')
  const injection = await client.submitIntent({ id: 'capability-injection-demo', type: 'terminate_instance',
    payload: { resourceId: 'i-0000001', targetAccountId: 'acc-demo' }, capabilities: lookup.capabilities, metadata })
  if (injection.errorCode !== 'CAPABILITY_MISMATCH_ERROR') throw new Error('Injection was not rejected')
  await client.submitIntent({ id: 'budget-source-demo', type: 'transfer', payload: { accountId: 'shared', amount: 150 }, metadata })
  const budget = await client.submitIntent({ id: 'temporal-budget-demo', type: 'transfer', payload: { accountId: 'shared', amount: 400 },
    metadata: { ...metadata, actor: 'second-agent' } })
  if (budget.errorCode !== 'TEMPORAL_CONSTRAINT_ERROR') throw new Error('Budget was not rejected')
  const directory = resolve('apps/replay-ui/src/fixtures')
  await mkdir(directory, { recursive: true })
  for (const id of ['capability-source-demo', 'capability-injection-demo', 'temporal-budget-demo']) {
    const replay = await client.replayIntent(id)
    if (!replay.integrity.valid) throw new Error('Invalid fixture chain')
    await writeFile(resolve(directory, `${id}.json`), JSON.stringify(replay, null, 2) + '\n')
  }
}

void main().catch(error => { console.error(error); process.exitCode = 1 })
